name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'  # Use the Temurin distribution (default)
      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test
      - name: Build and test with Maven
        run: mvn clean package

      # Step 4: Deploy the application to the Droplet
      - name: Deploy to Droplet
        run: |
          scp -o StrictHostKeyChecking=no target/*.jar root@167.71.72.179:/home/alina.jar
          ssh -o StrictHostKeyChecking=no root@167.71.72.179 <<EOF
          sudo systemctl stop alina || true
          sudo systemctl start alina
          EOF