name: Build and Test with Docker Compose Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Check Docker Compose Plugin
      - name: Check Docker Compose Plugin
        run: docker compose version

      # Step 4: Build and run services using Docker Compose
      - name: Build and run tests
        run: docker compose up --abort-on-container-exit --exit-code-from app

      # Step 5: Tear down services
      - name: Tear down services
        run: docker compose down