name: Build and Verify Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and verify using Docker Compose
      - name: Build and verify application
        run: docker-compose up --abort-on-container-exit --exit-code-from app

      # Step 4: Tear down services
      - name: Tear down services
        run: docker-compose down