name: Build and Test with Docker Compose Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Enable Docker Compose plugin
      - name: Enable Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      # Step 3: Run tests using Docker Compose
      - name: Run tests
        run: docker compose up --abort-on-container-exit --exit-code-from app

      # Step 4: Tear down services
      - name: Tear down services
        run: docker compose down